# .github/dependabot.yml

version: 2
updates:
  # Maintain dependencies for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt or setup.py
    schedule:
      interval: "weekly"
    # Optionally, specify the name of your requirements file
    # open-pull-requests-limit: 10
    # labels:
    #   - "dependencies"
    #   - "python"
